version: '4.29'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456

  elasticsearch:
    image: elasticsearch:8.13.0
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
      xpack.security.http.ssl.enabled: "false"
      xpack.security.transport.ssl.enabled: "false"

  er-s3:
    image: minio/minio:RELEASE.2024-05-07T06-41-25Z
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: ER-MINIO
      MINIO_ROOT_PASSWORD: ER-MINIO-PASS
    command: server --console-address ":9001" /data
    volumes:
      - ./minio_storage:/data
    restart: always
